services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: myPassword
      POSTGRES_DB: fitness_app
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d fitness_app"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
